# Generated by Django 2.0.4 on 2018-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_entry_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_type',
        ),
    ]
